[project]
name = "bitcoin-nft-backed-loan"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/stx-next-gen-memecoin/bitcoin-nft-backed-loan/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.bitcoin-nft-backed-loan]
path = "contracts/bitcoin-nft-backed-loan.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
